const debug = process.env.NODE_ENV !== 'production'
const state = {
  system: wx.getSystemInfoSync().system,
  from: '',
  loading: false,
  showInvalid: 2,
  loadMoreLoading: false,
  pageInfo: {},
  listLen: '',
  appid: debug ? 'wxf89d5b30a2a94598' : 'wxa0dca6753e065ea3',
  userInfo: {},
  token: '',
  openId: '',
  labelList: [],
  videoPageList: {},
  seriesRecommendList: {},
  videoRecommendList: {},
  seriesPageList: {},
  todayLiveList: [],
  videoDetails: {},
  liveDetails: {},
  seriesDetail: {},
  couponList: [],
  headVideoInfo: {},
  personalInfo: {},
  collectNewsList: [],
  collectLiveList: [],
  collectVideoList: [],
  collectSeriesList: [],
  collectMeetingList: [],
  unpayLiveList: [],
  unpayVideoList: [],
  unpaySeriesList: [],
  payLiveList: [],
  payVideoList: [],
  paySeriesList: [],
  videoRelatedList: [],
  commentList: [],
  seriesCommentList: [],
  couponsList: [],
  followStatus: false,
  collectionStatus: false,
  zanStatus: false,
  liveRelatedList: [],
  liveRelatedForeshowList: [],
  couponId: '' // 优惠券id
}
export default state
